[build]
buildCommand = """
pip install -r requirements.txt && \
OEMER_PATH=$(python -c "import oemer; import os; print(os.path.dirname(oemer.__file__))") && \
mkdir -p $OEMER_PATH/checkpoints/unet_big $OEMER_PATH/checkpoints/seg_net && \
wget -O $OEMER_PATH/checkpoints/unet_big/model.onnx https://github.com/BreezeWhite/oemer/releases/download/checkpoints/1st_model.onnx && \
wget -O $OEMER_PATH/checkpoints/unet_big/weights.h5 https://github.com/BreezeWhite/oemer/releases/download/checkpoints/1st_weights.h5 && \
wget -O $OEMER_PATH/checkpoints/seg_net/model.onnx https://github.com/BreezeWhite/oemer/releases/download/checkpoints/2nd_model.onnx && \
wget -O $OEMER_PATH/checkpoints/seg_net/weights.h5 https://github.com/BreezeWhite/oemer/releases/download/checkpoints/2nd_weights.h5
"""

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"